dist: xenial
branches:
  only:
    - master
services: mongodb
addons:
  chrome: stable # make Chrome available
language: node_js
nodejs:
  - 'lts/*'
  - '12'
before_install:
  - yarn global add @lhci/cli@0.3.x # install LHCI
script:
  - yarn build # build your site
  - yarn test # run your normal tests
after_success:
  - lhci autorun --upload.target=temporary-public-storage --upload.githubAppToken=$LHCI_GITHUB_APP_TOKEN --collect.staticDistDir="./.nuxt" # run lighthouse CI against your site
cache:
  yarn: true
  directories:
    - ~/.cache
notifications:
  email: false
